---
- name: "setup zabbix client "
  hosts: midt_automater
  gather_facts: True
  tasks:
  - name: "add zabbix client to inventory"
    vars:
      - ZABBIX_AGENT: "test"
    include_role:
      name: addzabbixagent

